### PR TITLE
Bump runtime to 42

### PR DESCRIPTION
**Pull request by bbhtt**
PIng @cunidev, please review when you have time, thanks!

### CODE REVIEW

**Comment by bbhtt** [comment]
bot, build

**Comment by bbhtt** [comment]
The icon size seems to be wrong:

`error: /srv/buildbot/worker/build-x86_64-6/build/builddir/export/share/icons/hicolor/16x16/apps/com.gitlab.cunidev.Workflow.png is not a valid icon: Expected a square icon but got: 16x15`

**Edit.** Looks like none of the icons except scalable have the correct size. appstream-compose can convert the scalable to required sizes and I don't think 16px, 22px, 24px, 32px, 48px and 256px icons are all necessary, so I'm patching the meson.build to not install the broken sizes rather than adding icons of each size. 

Opened https://gitlab.com/cunidev/workflow/-/issues/3

**Comment by bbhtt** [comment]
I can't reproduce the build failure locally, so hopefully this works.

**Comment by cunidev** [comment]
Works for me. Thanks!

**Pull request merged**
